name: thani_ui
description: A simple Angular 2 Web UI app
version: 0.0.1
environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular2: "^3.1.0"

dev_dependencies:
  browser: "^0.10.0+2"
  http: "^0.11.3+14"
  dart_to_js_script_rewriter: "^1.0.3"
  stream_transformers: "^0.3.0+3"
  test: "^0.12.24"
  #angular_test: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
- test/pub_serve:
    $include: test/**_test{.*,}.dart